[package]
name = "ace-rs"
version = "0.1.0"
authors = ["kamui-7 <65237048+kamui-7@users.noreply.github.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "2.33.3"
toml = "0.5.8"
genanki-rs = "0.1.2"
serde = "1.0.130"
serde_derive = "1.0.130"
