words_file = "/home/user/words.txt"
failed_words_file = "/home/user/failed_words.txt"

[anki]
deck = "Testing"
model = "Vocab Cards"
word_field = "Word"
sent_field = "Expression"
dict_field = "Meaning"
img_field = "Picture"
audio_field = "Audio"

[ankiconnect]
port = 8765
address = "127.0.0.1"

[dict."jmdict"]
enabled = true
priority = 0
fallback = true

[dict."shinmeikai"]
enabled = true
priority = 4
fallback = false

[lookup]
sort_freq = true

[media]
custom_audio_dir = "/home/user/Audio Bank"
regex = "- %word%.mp3$"
fallback_forvo = false
bail_on_empty = true
limit = 1
